# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('small_image_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('search_engine', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_url', models.CharField(blank=True, max_length=200, null=True)),
                ('relevance', models.PositiveIntegerField(blank=True, null=True)),
                ('life_expiration', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('is_done', models.IntegerField(default=False)),
                ('spider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='image_aggregator.Task'),
        ),
    ]
