# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_phrase', models.CharField(blank=True, max_length=255, null=True)),
                ('search_state', models.IntegerField(choices=[(0, 'Process'), (1, 'Have results'), (2, 'Done')], default=0)),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('engine_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
